export interface WordData {
    clue: string;
    answer: string;
    roots: RootsData[];
    definition: string;
    authorsNote?: string;
    partOfSpeech: string;
}

export interface RootsData {
    english: string;
    languageName: string;
    languageWord: string;
}

// 3 easy, 2 medium, 2 hard per week
export const WORD_LIST: WordData[] = [
    // New week
    {
        clue: "far vision", 
        answer: "television", 
        roots: [{ english: "far", languageName: "Greek", languageWord: "tele-" }, { english: "vision", languageName: "Latin", languageWord: "visio" }],
        definition: "technology with a screen",
        partOfSpeech: "noun",
    },
    { 
        clue: "life writing", 
        answer: "biography", 
        roots: [{ english: "life", languageName: "Greek", languageWord: "bios" }, { english: "writing", languageName: "Greek", languageWord: "-graphia" }],
        definition: "an account of someone's life",
        partOfSpeech: "noun",
    },
    {
        clue: "start from",
        answer: "originate", 
        roots: [{ english: "beginning, source", languageName: "Latin", languageWord: "originem" }],
        definition: "come from",
        partOfSpeech: "verb",
    },
    { 
        clue: "spiral wing", 
        answer: "helicopter", 
        roots: [{ english: "spiral", languageName: "Greek", languageWord: "helix" }, { english: "wing", languageName: "Greek", languageWord: "pteron" }],
        definition: "a type of aircraft",
        partOfSpeech: "noun",
    },
    {
        clue: "harbor wave",
        answer: "tsunami", 
        roots: [{ english: "harbor", languageName: "Japanese", languageWord: "tsu" }, { english: "wave", languageName: "Japanese", languageWord: "nami" }],
        definition: "a big wave",
        partOfSpeech: "noun",
    },
    { 
        clue: "lord of the world", 
        answer: "juggernaut", 
        roots: [{ english: "the world", languageName: "Sanskrit", languageWord: "jagat" }, { english: "lord", languageName: "Sanskrit", languageWord: "natha" }],
        definition: "a huge or overwhelming force",
        partOfSpeech: "noun",
    },
    {
        clue: "joy from harm",
        answer: "Schadenfreude", 
        roots: [{ english: "harm", languageName: "German", languageWord: "Schaden" }, { english: "joy", languageName: "German", languageWord: "Freude" }],
        definition: "joy from harm to others",
        partOfSpeech: "noun",
    },
    // New week
    {
        clue: "small-seeing instrument",
        answer: "microscope", 
        roots: [{ english: "small", languageName: "Latin", languageWord: "micro-" }, { english: "seeing instrument", languageName: "Latin", languageWord: "-scopium" }],
        definition: "an instrument to see very small objects",
        partOfSpeech: "noun",
    },
    {
        clue: "flesh devourer",
        answer: "carnivore",
        roots: [{ english: "flesh", languageName: "Latin", languageWord: "carni" }, { english: "devour", languageName: "Latin", languageWord: "vore" }],
        definition: "one that eats meat",
        partOfSpeech: "noun",
    },
    {
        clue: "measurement of three angles",
        answer: "trigonometry",
        roots: [{ english: "three", languageName: "Greek", languageWord: "tri"}, { english: "angles", languageName: "Greek", languageWord: "gonia"}, { english: "measurement", languageName: "Greek", languageWord: "metron"}],
        definition: "a branch of math",
        partOfSpeech: "noun",
    },
    {
        clue: "running back again",
        answer: "palindrome",
        roots: [{ english: "again", languageName: "Greek", languageWord: "palin"}, { english: "running", languageName: "Greek", languageWord: "dromos"}],
        definition: "a word the same backwards as forwards",
        partOfSpeech: "noun",
    },
    {
        clue: "forbidden",
        answer: "taboo",
        roots: [{ english: "forbidden", languageName: "Tongan", languageWord: "tapu"}],
        definition: "socially unacceptable",
        partOfSpeech: "noun, adjective",
        authorsNote: "This word appears in many Polynesian languages, not just Tongan."
    },
    {
        clue: "journey",
        answer: "safari",
        roots: [{ english: "journey", languageName: "Arabic", languageWord: "safar"}],
        definition: "an expedition in Africa",
        partOfSpeech: "noun",
    },
    {
        clue: "army cry",
        answer: "slogan",
        roots: [{ english: "army", languageName: "Gaelic", languageWord: "slua"}, { english: "cry", languageName: "Gaelic", languageWord: "ghairm"}],
        definition: "a memorable phrase or motto",
        partOfSpeech: "noun",
    },
    // New week
    {
        clue: "two wheels",
        answer: "bicycle", 
        roots: [{ english: "two", languageName: "Greek", languageWord: "bi-" }, { english: "wheel", languageName: "Greek", languageWord: "kyklos" }],
        definition: "a two-wheeled transport",
        partOfSpeech: "noun",
    },
    {
        clue: "star sailor",
        answer: "astronaut", 
        roots: [{ english: "star", languageName: "Greek", languageWord: "astro" }, { english: "sailor", languageName: "Greek", languageWord: "naut" }],
        definition: "one exploring space",
        partOfSpeech: "noun",
    },
    {
        clue: "beyond reality",
        answer: "surrealism", 
        roots: [{ english: "beyond", languageName: "French", languageWord: "sur" }, { english: "reality", languageName: "French", languageWord: "realisme" }],
        definition: "bizarre and dreamlike art",
        partOfSpeech: "noun",
    },
    {
        clue: "Sax's sound",
        answer: "saxophone",
        roots: [{ english: "Sax (surname)", languageName: "French", languageWord: "Sax"}, { english: "sound", languageName: "Greek", languageWord: "phone"}],
        definition: "type of woodwind instrument",
        partOfSpeech: "noun",
    },
    {
        clue: "empty orchestra",
        answer: "karaoke", 
        roots: [{ english: "empty", languageName: "Japanese", languageWord: "kara" }, { english: "orchestra", languageName: "Japanese", languageWord: "oke" }],
        definition: "singing with just the music",
        partOfSpeech: "noun",
    },
    {
        clue: "fast walker",
        answer: "giraffe",
        roots: [{english: "fast walker",languageName: "Arabic", languageWord: "zarafa"}],
        definition: "a tall, long-necked animal",
        partOfSpeech: "noun",
    },
    {
        clue: "know apart",
        answer: "diagnosis",
        roots: [{english: "apart",languageName: "Greek",languageWord: "dia"},{english: "knowledge",languageName: "Greek",languageWord: "gnosis"}],
        definition: "identification of a condition or problem",
        partOfSpeech: "noun",
    },
    // New week
    {
        clue: "one marriage",
        answer: "monogamy",
        roots: [{ english: "one", languageName: "Greek", languageWord: "monos"}, { english: "marriage", languageName: "Greek", languageWord: "gamos"}],
        definition: "one marriage at one time",
        partOfSpeech: "noun",
    },
    {
        clue: "fear of spiders",
        answer: "arachnophobia",
        roots: [{ english: "spider", languageName: "Greek", languageWord: "arakhne"}, { english: "fear", languageName: "Greek", languageWord: "phobia"}],
        definition: "literally fear of spiders",
        partOfSpeech: "noun",
    },
    {
        clue: "hand writing",
        answer: "manuscript",
        roots: [{english: "hand",languageName: "Latin",languageWord: "manus"},{english: "to write",languageName: "Latin",languageWord: "scribere"}],
        definition: "a handwritten document",
        partOfSpeech: "noun",
    },
    {
        clue: "self moving",
        answer: "automaton",
        roots: [{english: "self",languageName: "Greek",languageWord: "auto"},{english: "moving",languageName: "Greek",languageWord: "matos"}],
        definition: "a machine that moves by itself",
        partOfSpeech: "noun",
    },
    {
        clue: "the spirit/essence",
        answer: "alcohol",
        roots: [{ english: "the", languageName: "Arabic", languageWord: "al" },{ english: "chemical spirit/essence", languageName: "Arabic", languageWord: "kohl" }],
        definition: "a drink",
        partOfSpeech: "noun",
        authorsNote: "There are several translations of \"kohl\", but I opted for this one since it's the closest to the English understanding of the term."
    },
    {
        clue: "sensing together",
        answer: "synesthesia",
        roots: [{ english: "together", languageName: "Greek", languageWord: "syn" }, { english: "sensation", languageName: "Greek", languageWord: "aisthesis" }],
        definition: "condition where the senses blend together",
        partOfSpeech: "noun",
    },
    {
        clue: "way of adapting the spirit",
        answer: "aikido",
        roots: [{ english: "together", languageName: "Japanese", languageWord: "ai" }, { english: "spirit", languageName: "Japanese", languageWord: "ki" }, { english: "way/path", languageName: "Japanese", languageWord: "do" }],
        definition: "martial art focused on harmony",
        partOfSpeech: "noun",
    },
    // New week
    {
        clue: "fire mountain",
        answer: "volcano",
        roots: [{ english: "fire, burning", languageName: "Latin", languageWord: "vulcanus" }],
        definition: "a mountain that erupts molten rock",
        partOfSpeech: "noun",
    },
    {
        clue: "ice hill",
        answer: "iceberg",
        roots: [{ english: "ice", languageName: "English", languageWord: "ice" }, { english: "hill/mountain", languageName: "Old Norse", languageWord: "berg" }],
        definition: "a large floating mass of ice",
        partOfSpeech: "noun",
    },
    {
        clue: "middle earth",
        answer: "Mediterranean",
        roots: [{ english: "middle", languageName: "Latin", languageWord: "medius" }, { english: "earth", languageName: "Latin", languageWord: "terra" }],
        definition: "region surrounding a large inland sea",
        partOfSpeech: "noun",
    },
    {
        clue: "house management",
        answer: "economy",
        roots: [{ english: "house", languageName: "Greek", languageWord: "oikos" }, { english: "manage/keep", languageName: "Greek", languageWord: "nemein" }],
        definition: "management of resources or wealth",
        partOfSpeech: "noun",
    },
    {
        clue: "study of secrets",
        answer: "cryptology",
        roots: [{ english: "secret", languageName: "Greek", languageWord: "kryptos" }, { english: "study", languageName: "Greek", languageWord: "logia" }],
        definition: "study of codes and secret communication",
        partOfSpeech: "noun",
    },
    {
        clue: "gold flower",
        answer: "chrysanthemum",
        roots: [{ english: "gold", languageName: "Greek", languageWord: "khrysos"}, { english: "flower", languageName: "Greek", languageWord: "anthemon"}],
        definition: "a variety of golden flower",
        partOfSpeech: "noun",
    },
    {
        clue: "the soda ashes",
        answer: "alkaline",
        roots: [{ english: "the", languageName: "Arabic", languageWord: "al"},{ english: "ashes of saltwort", languageName: "Arabic", languageWord: "qaly" }],
        definition: "having a high pH",
        partOfSpeech: "adjective",
    },
    // new week
    {
        clue: "hundred foot",
        answer: "centipede",
        roots: [{ english: "hundred", languageName: "Latin", languageWord: "centum" }, { english: "foot", languageName: "Latin", languageWord: "ped" }],
        definition: "insect with many legs",
        partOfSpeech: "noun",
    },
    {
        clue: "mind healer",
        answer: "psychiatrist",
        roots: [{ english: "mind", languageName: "Greek", languageWord: "psyche" }, { english: "healing, care", languageName: "Greek", languageWord: "iatreia" }],
        definition: "a doctor specializing in mental health",
        partOfSpeech: "noun",
    },
    {
        clue: "the sun stands still",
        answer: "solstice",
        roots: [{ english: "sun", languageName: "Latin", languageWord: "sol" }, { english: "stand still", languageName: "Latin", languageWord: "sistere" }],
        definition: "when the sun reaches its highest or lowest point",
        partOfSpeech: "noun",
        authorsNote: "This root meaning is so cool."
    }, 
    {
        clue: "the king is helpless",
        answer: "checkmate",
        roots: [{ english: "king", languageName: "Persian", languageWord: "shah"}, { english: "helpless, astonished", languageName: "Persian", languageWord: "mat"}],
        definition: "a losing position in chess",
        partOfSpeech: "noun",
    },
    {
        clue: "sacred carvings",
        answer: "hieroglyphics",
        roots: [{ english: "sacred", languageName: "Greek", languageWord: "hieros"}, { english: "carving", languageName: "Greek", languageWord: "glyph"}],
        definition: "ancient Egyptian writing",
        partOfSpeech: "noun",
    },
    {
        clue: "expert, sorcerer",
        answer: "kahuna",
        roots: [{ english: "master, sorcerer, doctor", languageName: "Hawaiian", languageWord: "kahuna"}],
        definition: "a very important person",
        partOfSpeech: "noun",
        authorsNote: "This word has many definitions, but all attribute to word to referencing some form of expert."
    },
    {
        clue: "fart goblin",
        answer: "pumpernickel",
        roots: [{ english: "fart", languageName: "German", languageWord: "pumper"}, { english: "goblin, devil", languageName: "German", languageWord: "nickel"}],
        definition: "type of dark rye bread",
        partOfSpeech: "noun",
        authorsNote: "I know this is a difficult one... but I saw \"fart goblin\" and knew I had to include it."
    },
    // new week
    {
        clue: "power from the people",
        answer: "democracy",
        roots: [{ english: "people", languageName: "Greek", languageWord: "demos" }, { english: "power", languageName: "Greek", languageWord: "kratia" }],
        definition: "government ruled by the people",
        partOfSpeech: "noun",
    },
    {
        clue: "earth heat",
        answer: "geothermal",
        roots: [{ english: "earth", languageName: "Greek", languageWord: "geo" }, { english: "heat", languageName: "Greek", languageWord: "therme" }],
        definition: "pertaining to heat from the earth",
        partOfSpeech: "adjective",
    },
    {
        clue: "viewing all",
        answer: "panorama",
        roots: [{ english: "all", languageName: "Greek", languageWord: "pan" }, { english: "view", languageName: "Greek", languageWord: "horama" }],
        definition: "a wide view of a surrounding area",
        partOfSpeech: "noun",
    },
    {
        clue: "hide away from",
        answer: "abscond",
        roots: [{ english: "away from", languageName: "Latin", languageWord: "ab" }, { english: "hide", languageName: "Latin", languageWord: "condere" }],
        definition: "depart suddenly",
        partOfSpeech: "verb",
    },
    {
        clue: "smoked chili",
        answer: "chipotle",
        roots: [{ english: "chili", languageName: "Nahuatl", languageWord: "chilli"}, { english: "smoke", languageName: "Nahuatl", languageWord: "poctli"}],
        definition: "a smoke-dried chili pepper",
        partOfSpeech: "noun",
    },
    {
        clue: "warrior wearing a bearskin shirt",
        answer: "berserker",
        roots: [{ english: "bear", languageName: "Old Norse", languageWord: "ber"}, { english: "shirt", languageName: "Old Norse", languageWord: "serkr"}],
        definition: "a Norse warrior",
        partOfSpeech: "noun",
    },
    {
        clue: "season",
        answer: "monsoon",
        roots: [{ english: "season", languageName: "Arabic", languageWord: "mausim" }],
        definition: "seasonal heavy rains",
        partOfSpeech: "noun",
    },
    // new week
    {
        clue: "folding paper",
        answer: "origami", 
        roots: [{ english: "folding", languageName: "Japanese", languageWord: "ori" }, { english: "paper", languageName: "Japanese", languageWord: "kami" }],
        definition: "the art of paper folding",
        partOfSpeech: "noun",
    },
    {
        clue: "turning",
        answer: "tornado",
        roots: [{ english: "to turn", languageName: "Spanish", languageWord: "tornar"}],
        definition: "a rotating storm",
        partOfSpeech: "noun",
    },
    {
        clue: "sound picture",
        answer: "sonogram",
        roots: [{ english: "sound", languageName: "Latin", languageWord: "sonus"}, { english: "picture", languageName: "Latin", languageWord: "-gram"}],
        definition: "medical imaging using sound",
        partOfSpeech: "noun",
    },
    {
        clue: "wanderer",
        answer: "planet",
        roots: [{ english: "wanderer", languageName: "Greek", languageWord: "planetos"}],
        definition: "celestial body that orbits a star",
        partOfSpeech: "noun",
        authorsNote: "This may be my favorite word origin; thinking of a planet as something that wanders is so poetic to me."
    },
    {
        clue: "ring",
        answer: "bagel",
        roots: [{ english: "ring", languageName: "Yiddish", languageWord: "beygl"}],
        definition: "a ring-shaped bread roll",
        partOfSpeech: "noun",
    },
    {
        clue: "singing wolf",
        answer: "cantaloupe",
        roots: [{ english: "sing", languageName: "Latin", languageWord: "canta"}, { english: "wolf", languageName: "Latin", languageWord: "lupus"}],
        definition: "a small melon",
        partOfSpeech: "noun",
        authorsNote: "Cantaloupe is named after the region where it was first grown, Cantalupo." 
    },
    {
        clue: "with a key",
        answer: "conclave",
        roots: [{ english: "with", languageName: "Latin", languageWord: "con" }, { english: "key", languageName: "Latin", languageWord: "clavis" }],
        definition: "where cardinals elect a new pope",
        partOfSpeech: "noun",
        authorsNote: "\"With a key\" refers to the fact that the cardinals are locked in the room."
    },
    // new week
    {
        clue: "ladder steps",
        answer: "escalate",
        roots: [{ english: "ladder", languageName: "Latin", languageWord: "scala" }],
        definition: "to increase in intensity",
        partOfSpeech: "verb",
    },
    {
        clue: "little wolf",
        answer: "coyote",
        roots: [{ english: "little wolf", languageName: "Nahuatl", languageWord: "coyotl" }],
        definition: "a wild dog of North America",
        partOfSpeech: "noun",
    },
    {
        clue: "lion's tooth (flower)",
        answer: "dandelion",
        roots: [{ english: "lion", languageName: "French", languageWord: "lion" }, { english: "tooth", languageName: "French", languageWord: "dent" }],
        definition: "a yellow flowering weed",
        partOfSpeech: "noun",
    },
    {
        clue: "dust colored",
        answer: "khaki",
        roots: [{ english: "dust colored", languageName: "Urdu", languageWord: "khaki" }],
        definition: "a tan or brown color",
        partOfSpeech: "noun, adjective",
    },
    {
        clue: "spirit of a dead person",
        answer: "zombie",
        roots: [{ english: "spirit of a dead person", languageName: "Kikongo", languageWord: "nzambi" }],
        definition: "an undead creature",
        authorsNote: "This term appears in other West African languages besides Kikongo.",
        partOfSpeech: "noun",
    },
    {
        clue: "badly suited to the purpose",
        answer: "malapropism",
        roots: [{ english: "badly", languageName: "French", languageWord: "mal" }, { english: "suited", languageName: "French", languageWord: "à propos" }],
        definition: "misuse of a word",
        partOfSpeech: "noun",
    },
    {
        clue: "great lord",
        answer: "tycoon",
        roots: [{ english: "great", languageName: "Japanese", languageWord: "tai" }, { english: "lord", languageName: "Japanese", languageWord: "kun" }],
        definition: "a wealthy business leader",
        partOfSpeech: "noun",
    },
    // new week
    {
        clue: "first two letters",
        answer: "alphabet",
        roots: [{ english: "alpha", languageName: "Greek", languageWord: "alpha" }, { english: "beta", languageName: "Greek", languageWord: "beta" }],
        definition: "letters of a language",
        partOfSpeech: "noun",
    },
    {
        clue: "commander of the sea",
        answer: "admiral",
        roots: [{ english: "commander", languageName: "Arabic", languageWord: "amir" }, { english: "sea", languageName: "Arabic", languageWord: "al-bahr" }],
        definition: "high-ranking naval officer",
        partOfSpeech: "noun",
    },
    {
        clue: "night demon",
        answer: "nightmare",
        roots: [{ english: "night", languageName: "Old English", languageWord: "niht" }, { english: "demon", languageName: "Old English", languageWord: "mare" }],
        definition: "a frightening dream",
        partOfSpeech: "noun",
    },
    {
        clue: "empty",
        answer: "zero",
        roots: [{ english: "empty", languageName: "Arabic", languageWord: "sifr" }],
        definition: "a quantity of nothing",
        partOfSpeech: "noun",
    },
    {
        clue: "of Pan",
        answer: "panic",
        roots: [{ english: "of Pan", languageName: "Greek", languageWord: "panikos" }],
        definition: "sudden overwhelming fear",
        partOfSpeech: "noun",
    },
    {
        clue: "shadow tailed (animal)",
        answer: "squirrel",
        roots: [{ english: "shadow", languageName: "Greek", languageWord: "skia" }, { english: "tail", languageName: "Greek", languageWord: "oura" }],
        definition: "a tree-climbing rodent",
        partOfSpeech: "noun",
    },
    {
        clue: "the restoration",
        answer: "algebra",
        roots: [{ english: "the", languageName: "Arabic", languageWord: "al" }, { english: "restoration", languageName: "Arabic", languageWord: "jabr" }],
        definition: "branch of mathematics",
        partOfSpeech: "noun",
    },
    // new week
    {
        clue: "bad air",
        answer: "malaria",
        roots: [{ english: "bad", languageName: "Italian", languageWord: "mala" }, { english: "air", languageName: "Italian", languageWord: "aria" }],
        definition: "a mosquito-borne disease",
        partOfSpeech: "noun",
    },
    {
        clue: "learned/skilled (person)",
        answer: "pundit",
        roots: [{ english: "learned/skilled", languageName: "Sanskrit", languageWord: "pandita" }],
        definition: "an expert commentator",
        partOfSpeech: "noun",
    },
    {
        clue: "sour wine",
        answer: "vinegar",
        roots: [{ english: "wine", languageName: "French", languageWord: "vin" }, { english: "sour", languageName: "French", languageWord: "aigre" }],
        definition: "acidic liquid used in cooking",
        partOfSpeech: "noun",
    },
    {
        clue: "testicle",
        answer: "avocado",
        roots: [{ english: "testicle", languageName: "Nahuatl", languageWord: "ahuacatl" }],
        definition: "a green fruit",
        authorsNote: "You'll never be able to unsee this now.",
        partOfSpeech: "noun",
    },
    {
        clue: "thanks/grace",
        answer: "mercy",
        roots: [{ english: "thanks/grace", languageName: "Old French", languageWord: "mercit" }],
        definition: "kindness and grace",
        authorsNote: "This comes from the same Latin as \"merchant\", meaning closer to \"reward\" as wages",
        partOfSpeech: "noun",
    },
    {
        clue: "wind eye",
        answer: "window",
        roots: [{ english: "wind", languageName: "Old Norse", languageWord: "vindr" }, { english: "eye", languageName: "Old Norse", languageWord: "auga" }],
        definition: "an opening in a wall",
        partOfSpeech: "noun",
    },
    {
        clue: "press/massage",
        answer: "shampoo",
        roots: [{ english: "press/massage", languageName: "Hindi", languageWord: "champo" }],
        definition: "hair cleaning product",
        partOfSpeech: "noun",
    },
    // new week
    {
        clue: "milk circle (visually)",
        answer: "galaxy",
        roots: [{ english: "milk", languageName: "Greek", languageWord: "gala" }, { english: "circle", languageName: "Greek", languageWord: "kyklos" }],
        definition: "a system of stars",
        partOfSpeech: "noun",
    },
    {
        clue: "Bengali (house)",
        answer: "bungalow",
        roots: [{ english: "Bengali", languageName: "Hindi", languageWord: "bangla" }],
        definition: "a single-story house",
        partOfSpeech: "noun",
    },
    {
        clue: "death pledge (financially)",
        answer: "mortgage",
        roots: [{ english: "death", languageName: "French", languageWord: "mort" }, { english: "pledge", languageName: "French", languageWord: "gage" }],
        definition: "a loan to buy property",
        partOfSpeech: "noun",
    },
    {
        clue: "nonsense (onomatopoeia)",
        answer: "barbarian",
        roots: [{ english: "(nonsense)", languageName: "Greek", languageWord: "bar-bar" }],
        definition: "an uncivilized person",
        authorsNote: "The Greeks thought foreign language just sounded like \"bar-bar\", so they called them barbarians.",
        partOfSpeech: "noun",
    },
    {
        clue: "to strike",
        answer: "tattoo",
        roots: [{ english: "to strike", languageName: "Tahitian", languageWord: "tatau" }],
        definition: "permanent ink design on skin",
        partOfSpeech: "noun",
    },
    {
        clue: "to lick",
        answer: "chutney",
        roots: [{ english: "to lick", languageName: "Hindi", languageWord: "chatni" }],
        definition: "a spicy condiment",
        partOfSpeech: "noun",
    },
    {
        clue: "fig (flattery) shower",
        answer: "sycophant",
        roots: [{ english: "fig", languageName: "Greek", languageWord: "sykon" }, { english: "shower", languageName: "Greek", languageWord: "phainein" }],
        definition: "a person who flatters",
        partOfSpeech: "noun",
    },
    // new week
    {
        clue: "god of wind",
        answer: "hurricane",
        roots: [{ english: "god of wind", languageName: "Taino", languageWord: "huracan" }],
        definition: "a powerful storm",
        partOfSpeech: "noun",
    },
    {
        clue: "apparition",
        answer: "phantom",
        roots: [{ english: "apparition", languageName: "Greek", languageWord: "phantazein" }],
        definition: "a ghost or apparition",
        partOfSpeech: "noun",
    },
    {
        clue: "deceiver/conman",
        answer: "thug",
        roots: [{ english: "deceiver/conman", languageName: "Hindi", languageWord: "thag" }],
        definition: "a violent criminal",
        partOfSpeech: "noun",
    },
    {
        clue: "ill star (omen)",
        answer: "disaster",
        roots: [{ english: "ill", languageName: "Latin", languageWord: "dis" }, { english: "star", languageName: "Latin", languageWord: "astrum" }],
        definition: "a catastrophic event",
        partOfSpeech: "noun",
    },
    {
        clue: "very disagreeable person",
        answer: "curmudgeon",
        roots: [{ english: "very (intensifier)", languageName: "Middle English", languageWord: "ker-" }, { english: "disagreeable person", languageName: "Middle English", languageWord: "muigean" }],
        definition: "a bad-tempered person",
        partOfSpeech: "noun",
    },
    {
        clue: "ghost (animal)",
        answer: "lemur",
        roots: [{ english: "ghost", languageName: "Latin", languageWord: "lemures" }],
        definition: "a primate from Madagascar",
        partOfSpeech: "noun",
    },
    {
        clue: "building (game)",
        answer: "jenga",
        roots: [{ english: "to build", languageName: "Swahili", languageWord: "jenga" }],
        definition: "a block-stacking game",
        partOfSpeech: "noun",
    },
    // new week
    {
        clue: "garlic oil",
        answer: "aioli",
        roots: [{ english: "garlic", languageName: "Provençal", languageWord: "ai" }, { english: "oil", languageName: "Provençal", languageWord: "oli" }],
        definition: "a garlic mayonnaise",
        partOfSpeech: "noun",
    },
    {
        clue: "citizen of the world",
        answer: "cosmopolitan",
        roots: [{ english: "world", languageName: "Greek", languageWord: "kosmos" }, { english: "citizen", languageName: "Greek", languageWord: "polites" }],
        definition: "worldly and sophisticated",
        partOfSpeech: "adjective",
    },
    {
        clue: "leg garment",
        answer: "pajamas",
        roots: [{ english: "leg", languageName: "Persian", languageWord: "pa" }, { english: "garment", languageName: "Persian", languageWord: "jama" }],
        definition: "sleepwear",
        authorsNote: "Similar roots appear in Hindi as well.",
        partOfSpeech: "noun",
    },
    {
        clue: "little shade",
        answer: "umbrella",
        roots: [{ english: "shade", languageName: "Latin", languageWord: "umbra" }],
        definition: "a portable shade device",
        partOfSpeech: "noun",
    },
    {
        clue: "forgetfulness",
        answer: "lethargy",
        roots: [{ english: "forgetfulness", languageName: "Greek", languageWord: "lethe" }],
        definition: "lack of energy",
        authorsNote: "In Greek mythology, the river Lethe was where you lost your memory.",
        partOfSpeech: "noun",
    },
    {
        clue: "water of life",
        answer: "whiskey",
        roots: [{ english: "water", languageName: "Gaelic", languageWord: "uisce" }, { english: "life", languageName: "Gaelic", languageWord: "beatha" }],
        definition: "an alcoholic spirit",
        partOfSpeech: "noun",
    },
    {
        clue: "forced labor",
        answer: "robot",
        roots: [{ english: "forced labor", languageName: "Czech", languageWord: "robota" }],
        definition: "an automated machine",
        partOfSpeech: "noun",
    },
    // new week
    {
        clue: "(person) to eat bread with",
        answer: "companion",
        roots: [{ english: "with", languageName: "Latin", languageWord: "com" }, { english: "bread", languageName: "Latin", languageWord: "panis" }],
        definition: "a friend or partner",
        partOfSpeech: "noun",
    },
    {
        clue: "let him beware",
        answer: "caveat",
        roots: [{ english: "let him beware", languageName: "Latin", languageWord: "caveat" }],
        definition: "a warning",
        partOfSpeech: "noun",
    },
    {
        clue: "long hair (visually)",
        answer: "comet",
        roots: [{ english: "long hair", languageName: "Greek", languageWord: "kometes" }],
        definition: "a celestial body with a tail",
        partOfSpeech: "noun",
    },
    {
        clue: "fish sauce",
        answer: "ketchup",
        roots: [{ english: "fish sauce", languageName: "Hokkien", languageWord: "kê-tsiap" }],
        definition: "a tomato-based condiment",
        authorsNote: "There are competing theories on the exact origin of this word, but most have a similar definition and are in this region.",
        partOfSpeech: "noun",
    },
    {
        clue: "three roads",
        answer: "trivia",
        roots: [{ english: "three", languageName: "Latin", languageWord: "tri" }, { english: "roads", languageName: "Latin", languageWord: "via" }],
        definition: "unimportant facts",
        partOfSpeech: "noun",
    },
    {
        clue: "white head (animal)",
        answer: "penguin",
        roots: [{ english: "white", languageName: "Welsh", languageWord: "pen" }, { english: "head", languageName: "Welsh", languageWord: "gwyn" }],
        definition: "a flightless seabird",
        partOfSpeech: "noun",
    },
    {
        clue: "master of the house",
        answer: "despot",
        roots: [{ english: "master", languageName: "Greek", languageWord: "despotes" }, { english: "house", languageName: "Greek", languageWord: "oikos" }],
        definition: "an absolute ruler",
        partOfSpeech: "noun",
    },
    // new week
    {
        clue: "pain to return home",
        answer: "nostalgia",
        roots: [{ english: "return home", languageName: "Greek", languageWord: "nostos" }, { english: "pain", languageName: "Greek", languageWord: "algos" }],
        definition: "longing for the past",
        partOfSpeech: "noun",
    },
    {
        clue: "teacher",
        answer: "guru",
        roots: [{ english: "teacher", languageName: "Sanskrit", languageWord: "guru" }],
        definition: "a spiritual teacher",
        partOfSpeech: "noun",
    },
    {
        clue: "river horse",
        answer: "hippopotamus",
        roots: [{ english: "horse", languageName: "Greek", languageWord: "hippos" }, { english: "river", languageName: "Greek", languageWord: "potamos" }],
        definition: "a large African mammal",
        partOfSpeech: "noun",
    },
    {
        clue: "forty days",
        answer: "quarantine",
        roots: [{ english: "forty", languageName: "Italian", languageWord: "quaranta" }],
        definition: "isolation to prevent disease",
        authorsNote: "\"Forty days\" referred to the length of the quarantine for ships in the harbor",
        partOfSpeech: "noun",
    },
    {
        clue: "hemp (cloth)",
        answer: "canvas",
        roots: [{ english: "hemp", languageName: "Greek", languageWord: "kannabis" }],
        definition: "a strong cloth material",
        partOfSpeech: "noun",
    },
    {
        clue: "headlong (place)",
        answer: "precipice",
        roots: [{ english: "headlong", languageName: "Latin", languageWord: "praeceps" }],
        definition: "a steep cliff",
        partOfSpeech: "noun",
    },
    {
        clue: "running wild",
        answer: "amok",
        roots: [{ english: "running wild", languageName: "Malay", languageWord: "amuk" }],
        definition: "in a frenzy",
        partOfSpeech: "adverb",
    }
];
